context:
  version: "2.9.0"

package:
  name: dbos
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/d/dbos/dbos-${{ version }}.tar.gz
    sha256: f4d80d3db9d410aa8a317db338cf189b2aa12009491ca3efe8e9582316be83ff

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - dbos = dbos.cli.cli:app
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml >=6.0.2
    - python-dateutil >=2.9.0.post0
    - psycopg >=3.1
    - websockets >=14.0
    - typer-slim >=0.17.4
    - sqlalchemy >=2.0.43

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - dbos
      pip_check: true

about:
  homepage: https://github.com/dbos-inc/dbos-transact-py
  summary: Ultra-lightweight durable execution in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
